In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline 

In [2]:
import warnings
warnings.filterwarnings('ignore')

# Input File

In [3]:
Data_train=pd.read_csv('./data/train.csv')

Data_test=pd.read_csv('./data/test.csv')

Data_train.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [4]:
Data_test.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0  1461          20       RH         80.0    11622   Pave   NaN      Reg   
1  1462          20       RL         81.0    14267   Pave   NaN      IR1   
2  1463          60       RL         74.0    13830   Pave   NaN      IR1   
3  1464          60       RL         78.0     9978   Pave   NaN      IR1   
4  1465         120       RL         43.0     5005   Pave   NaN      IR1   

  LandContour Utilities  ... ScreenPorch PoolArea PoolQC  Fence MiscFeature  \
0         Lvl    AllPub  ...         120        0    NaN  MnPrv         NaN   
1         Lvl    AllPub  ...           0        0    NaN    NaN        Gar2   
2         Lvl    AllPub  ...           0        0    NaN  MnPrv         NaN   
3         Lvl    AllPub  ...           0        0    NaN    NaN         NaN   
4         HLS    AllPub  ...         144        0    NaN    NaN         NaN   

  MiscVal MoSold  YrSold  SaleType  SaleCondition  
0       0      6    2010        WD         Normal  
1   12500      6    2010        WD         Normal  
2       0      3    2010        WD         Normal  
3       0      6    2010        WD         Normal  
4       0      1    2010        WD         Normal  

[5 rows x 80 columns]

In [5]:
AllData=pd.concat([Data_train,Data_test])

In [6]:
AllData.head()

1stFlrSF  2ndFlrSF  3SsnPorch Alley  BedroomAbvGr BldgType BsmtCond  \
0       856       854          0   NaN             3     1Fam       TA   
1      1262         0          0   NaN             3     1Fam       TA   
2       920       866          0   NaN             3     1Fam       TA   
3       961       756          0   NaN             3     1Fam       Gd   
4      1145      1053          0   NaN             4     1Fam       TA   

  BsmtExposure  BsmtFinSF1  BsmtFinSF2  ... SaleType ScreenPorch  Street  \
0           No       706.0         0.0  ...       WD           0    Pave   
1           Gd       978.0         0.0  ...       WD           0    Pave   
2           Mn       486.0         0.0  ...       WD           0    Pave   
3           No       216.0         0.0  ...       WD           0    Pave   
4           Av       655.0         0.0  ...       WD           0    Pave   

   TotRmsAbvGrd TotalBsmtSF  Utilities WoodDeckSF YearBuilt YearRemodAdd  \
0             8       856.0     AllPub          0      2003         2003   
1             6      1262.0     AllPub        298      1976         1976   
2             6       920.0     AllPub          0      2001         2002   
3             7       756.0     AllPub          0      1915         1970   
4             9      1145.0     AllPub        192      2000         2000   

  YrSold  
0   2008  
1   2007  
2   2008  
3   2006  
4   2008  

[5 rows x 81 columns]

In [7]:
AllData.isnull().sum()[AllData.isnull().sum()>0].sort_values()

GarageArea         1
SaleType           1
KitchenQual        1
BsmtFinSF1         1
BsmtFinSF2         1
GarageCars         1
TotalBsmtSF        1
Exterior2nd        1
Exterior1st        1
BsmtUnfSF          1
Electrical         1
Functional         2
Utilities          2
BsmtHalfBath       2
BsmtFullBath       2
MSZoning           4
MasVnrArea        23
MasVnrType        24
BsmtFinType1      79
BsmtFinType2      80
BsmtQual          81
BsmtCond          82
BsmtExposure      82
GarageType       157
GarageYrBlt      159
GarageFinish     159
GarageCond       159
GarageQual       159
LotFrontage      486
FireplaceQu     1420
SalePrice       1459
Fence           2348
Alley           2721
MiscFeature     2814
PoolQC          2909
dtype: int64

# 空值處理 

## All fill mean

In [8]:
"""
t=AllData.isnull().sum()
#all 1460 entries
t=t[t>0].sort_values(ascending=False)
t=t/2919
t=pd.DataFrame(t)
sns.set(rc={'figure.figsize':(15,10)})
sns.set(font_scale=1.5)
a=sns.barplot(x=t.index,y=t[0],data=t).set_title('Null number ratio')
plt.xticks(rotation=75)"""

"\nt=AllData.isnull().sum()\n#all 1460 entries\nt=t[t>0].sort_values(ascending=False)\nt=t/2919\nt=pd.DataFrame(t)\nsns.set(rc={'figure.figsize':(15,10)})\nsns.set(font_scale=1.5)\na=sns.barplot(x=t.index,y=t[0],data=t).set_title('Null number ratio')\nplt.xticks(rotation=75)"

In [9]:
AllData.info()
#分成3類 : float, int, object

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 81 columns):
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
3SsnPorch        2919 non-null int64
Alley            198 non-null object
BedroomAbvGr     2919 non-null int64
BldgType         2919 non-null object
BsmtCond         2837 non-null object
BsmtExposure     2837 non-null object
BsmtFinSF1       2918 non-null float64
BsmtFinSF2       2918 non-null float64
BsmtFinType1     2840 non-null object
BsmtFinType2     2839 non-null object
BsmtFullBath     2917 non-null float64
BsmtHalfBath     2917 non-null float64
BsmtQual         2838 non-null object
BsmtUnfSF        2918 non-null float64
CentralAir       2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
Electrical       2918 non-null object
EnclosedPorch    2919 non-null int64
ExterCond        2919 non-null object
ExterQual        2919 non-null object
Exterior1st      291

In [10]:
AllData['1stFlrSF'].dtypes

dtype('int64')

In [11]:
intClass=[]
floatClass=[]
objectClass=[]
allClass=AllData.columns
def classifyType(allCol):
    for col in allCol:
        thisClass=AllData[col].dtypes
        if(thisClass=='int64'):
            intClass.append(col)
        elif(thisClass=='float64'):
            floatClass.append(col)
        elif(thisClass=='object'):
            objectClass.append(col)
        else:
            raise Exception('Un-handdle data type')

In [12]:
classifyType(allClass)

In [13]:
AllData[intClass].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 26 columns):
1stFlrSF         2919 non-null int64
2ndFlrSF         2919 non-null int64
3SsnPorch        2919 non-null int64
BedroomAbvGr     2919 non-null int64
EnclosedPorch    2919 non-null int64
Fireplaces       2919 non-null int64
FullBath         2919 non-null int64
GrLivArea        2919 non-null int64
HalfBath         2919 non-null int64
Id               2919 non-null int64
KitchenAbvGr     2919 non-null int64
LotArea          2919 non-null int64
LowQualFinSF     2919 non-null int64
MSSubClass       2919 non-null int64
MiscVal          2919 non-null int64
MoSold           2919 non-null int64
OpenPorchSF      2919 non-null int64
OverallCond      2919 non-null int64
OverallQual      2919 non-null int64
PoolArea         2919 non-null int64
ScreenPorch      2919 non-null int64
TotRmsAbvGrd     2919 non-null int64
WoodDeckSF       2919 non-null int64
YearBuilt        2919 non-null int64
YearR

In [14]:
AllData[floatClass].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 12 columns):
BsmtFinSF1      2918 non-null float64
BsmtFinSF2      2918 non-null float64
BsmtFullBath    2917 non-null float64
BsmtHalfBath    2917 non-null float64
BsmtUnfSF       2918 non-null float64
GarageArea      2918 non-null float64
GarageCars      2918 non-null float64
GarageYrBlt     2760 non-null float64
LotFrontage     2433 non-null float64
MasVnrArea      2896 non-null float64
SalePrice       1460 non-null float64
TotalBsmtSF     2918 non-null float64
dtypes: float64(12)
memory usage: 296.5 KB


In [15]:
AllData[floatClass]=AllData[floatClass].fillna(AllData.mean())

In [16]:
AllData[objectClass].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2919 entries, 0 to 1458
Data columns (total 43 columns):
Alley            198 non-null object
BldgType         2919 non-null object
BsmtCond         2837 non-null object
BsmtExposure     2837 non-null object
BsmtFinType1     2840 non-null object
BsmtFinType2     2839 non-null object
BsmtQual         2838 non-null object
CentralAir       2919 non-null object
Condition1       2919 non-null object
Condition2       2919 non-null object
Electrical       2918 non-null object
ExterCond        2919 non-null object
ExterQual        2919 non-null object
Exterior1st      2918 non-null object
Exterior2nd      2918 non-null object
Fence            571 non-null object
FireplaceQu      1499 non-null object
Foundation       2919 non-null object
Functional       2917 non-null object
GarageCond       2760 non-null object
GarageFinish     2760 non-null object
GarageQual       2760 non-null object
GarageType       2762 non-null object
Heating          2919

In [17]:
AllData[objectClass]=AllData[objectClass].fillna('None')

In [18]:
AllData

1stFlrSF  2ndFlrSF  3SsnPorch Alley  BedroomAbvGr BldgType BsmtCond  \
0          856       854          0  None             3     1Fam       TA   
1         1262         0          0  None             3     1Fam       TA   
2          920       866          0  None             3     1Fam       TA   
3          961       756          0  None             3     1Fam       Gd   
4         1145      1053          0  None             4     1Fam       TA   
...        ...       ...        ...   ...           ...      ...      ...   
1454       546       546          0  None             3    Twnhs       TA   
1455       546       546          0  None             3   TwnhsE       TA   
1456      1224         0          0  None             4     1Fam       TA   
1457       970         0          0  None             3     1Fam       TA   
1458       996      1004          0  None             3     1Fam       TA   

     BsmtExposure  BsmtFinSF1  BsmtFinSF2  ... SaleType ScreenPorch  Street  \
0              No       706.0         0.0  ...       WD           0    Pave   
1              Gd       978.0         0.0  ...       WD           0    Pave   
2              Mn       486.0         0.0  ...       WD           0    Pave   
3              No       216.0         0.0  ...       WD           0    Pave   
4              Av       655.0         0.0  ...       WD           0    Pave   
...           ...         ...         ...  ...      ...         ...     ...   
1454           No         0.0         0.0  ...       WD           0    Pave   
1455           No       252.0         0.0  ...       WD           0    Pave   
1456           No      1224.0         0.0  ...       WD           0    Pave   
1457           Av       337.0         0.0  ...       WD           0    Pave   
1458           Av       758.0         0.0  ...       WD           0    Pave   

      TotRmsAbvGrd TotalBsmtSF  Utilities WoodDeckSF YearBuilt YearRemodAdd  \
0                8       856.0     AllPub          0      2003         2003   
1                6      1262.0     AllPub        298      1976         1976   
2                6       920.0     AllPub          0      2001         2002   
3                7       756.0     AllPub          0      1915         1970   
4                9      1145.0     AllPub        192      2000         2000   
...            ...         ...        ...        ...       ...          ...   
1454             5       546.0     AllPub          0      1970         1970   
1455             6       546.0     AllPub          0      1970         1970   
1456             7      1224.0     AllPub        474      1960         1996   
1457             6       912.0     AllPub         80      1992         1992   
1458             9       996.0     AllPub        190      1993         1994   

     YrSold  
0      2008  
1      2007  
2      2008  
3      2006  
4      2008  
...     ...  
1454   2006  
1455   2006  
1456   2006  
1457   2006  
1458   2006  

[2919 rows x 81 columns]

# Faeatures Engineer

# Select Faeatures (All) Encoding

In [19]:
AllData=AllData[Data_train.columns]

In [21]:
AllData[intClass]
for i in intClass:
    if(len(AllData[i].unique())<20):
        print(i)
        print(AllData[i].unique())

BedroomAbvGr
[3 4 1 2 0 5 6 8]
Fireplaces
[0 1 2 3 4]
FullBath
[2 1 3 0 4]
HalfBath
[1 0 2]
KitchenAbvGr
[1 2 3 0]
MSSubClass
[ 60  20  70  50 190  45  90 120  30  85  80 160  75 180  40 150]
MoSold
[ 2  5  9 12 10  8 11  4  1  7  3  6]
OverallCond
[5 8 6 7 4 2 3 9 1]
OverallQual
[ 7  6  8  5  9  4 10  3  1  2]
PoolArea
[  0 512 648 576 555 480 519 738 144 368 444 228 561 800]
TotRmsAbvGrd
[ 8  6  7  9  5 11  4 10 12  3  2 14 13 15]
YrSold
[2008 2007 2006 2009 2010]


In [22]:
AllData[intClass]

1stFlrSF  2ndFlrSF  3SsnPorch  BedroomAbvGr  EnclosedPorch  Fireplaces  \
0          856       854          0             3              0           0   
1         1262         0          0             3              0           1   
2          920       866          0             3              0           1   
3          961       756          0             3            272           1   
4         1145      1053          0             4              0           1   
...        ...       ...        ...           ...            ...         ...   
1454       546       546          0             3              0           0   
1455       546       546          0             3              0           0   
1456      1224         0          0             4              0           1   
1457       970         0          0             3              0           0   
1458       996      1004          0             3              0           1   

      FullBath  GrLivArea  HalfBath    Id  ...  OpenPorchSF  OverallCond  \
0            2       1710         1     1  ...           61            5   
1            2       1262         0     2  ...            0            8   
2            2       1786         1     3  ...           42            5   
3            1       1717         0     4  ...           35            5   
4            2       2198         1     5  ...           84            5   
...        ...        ...       ...   ...  ...          ...          ...   
1454         1       1092         1  2915  ...            0            7   
1455         1       1092         1  2916  ...           24            5   
1456         1       1224         0  2917  ...            0            7   
1457         1        970         0  2918  ...           32            5   
1458         2       2000         1  2919  ...           48            5   

      OverallQual  PoolArea  ScreenPorch  TotRmsAbvGrd  WoodDeckSF  YearBuilt  \
0               7         0            0             8           0       2003   
1               6         0            0             6         298       1976   
2               7         0            0             6           0       2001   
3               7         0            0             7           0       1915   
4               8         0            0             9         192       2000   
...           ...       ...          ...           ...         ...        ...   
1454            4         0            0             5           0       1970   
1455            4         0            0             6           0       1970   
1456            5         0            0             7         474       1960   
1457            5         0            0             6          80       1992   
1458            7         0            0             9         190       1993   

      YearRemodAdd  YrSold  
0             2003    2008  
1             1976    2007  
2             2002    2008  
3             1970    2006  
4             2000    2008  
...            ...     ...  
1454          1970    2006  
1455          1970    2006  
1456          1996    2006  
1457          1992    2006  
1458          1994    2006  

[2919 rows x 26 columns]

In [23]:
AllData[floatClass]

BsmtFinSF1  BsmtFinSF2  BsmtFullBath  BsmtHalfBath  BsmtUnfSF  \
0          706.0         0.0           1.0           0.0      150.0   
1          978.0         0.0           0.0           1.0      284.0   
2          486.0         0.0           1.0           0.0      434.0   
3          216.0         0.0           1.0           0.0      540.0   
4          655.0         0.0           1.0           0.0      490.0   
...          ...         ...           ...           ...        ...   
1454         0.0         0.0           0.0           0.0      546.0   
1455       252.0         0.0           0.0           0.0      294.0   
1456      1224.0         0.0           1.0           0.0        0.0   
1457       337.0         0.0           0.0           1.0      575.0   
1458       758.0         0.0           0.0           0.0      238.0   

      GarageArea  GarageCars  GarageYrBlt  LotFrontage  MasVnrArea  \
0          548.0         2.0  2003.000000         65.0       196.0   
1          460.0         2.0  1976.000000         80.0         0.0   
2          608.0         2.0  2001.000000         68.0       162.0   
3          642.0         3.0  1998.000000         60.0         0.0   
4          836.0         3.0  2000.000000         84.0       350.0   
...          ...         ...          ...          ...         ...   
1454         0.0         0.0  1978.113406         21.0         0.0   
1455       286.0         1.0  1970.000000         21.0         0.0   
1456       576.0         2.0  1960.000000        160.0         0.0   
1457         0.0         0.0  1978.113406         62.0         0.0   
1458       650.0         3.0  1993.000000         74.0        94.0   

         SalePrice  TotalBsmtSF  
0     208500.00000        856.0  
1     181500.00000       1262.0  
2     223500.00000        920.0  
3     140000.00000        756.0  
4     250000.00000       1145.0  
...            ...          ...  
1454  180921.19589        546.0  
1455  180921.19589        546.0  
1456  180921.19589       1224.0  
1457  180921.19589        912.0  
1458  180921.19589        996.0  

[2919 rows x 12 columns]

In [24]:
AllData[objectClass]

Alley BldgType BsmtCond BsmtExposure BsmtFinType1 BsmtFinType2 BsmtQual  \
0     None     1Fam       TA           No          GLQ          Unf       Gd   
1     None     1Fam       TA           Gd          ALQ          Unf       Gd   
2     None     1Fam       TA           Mn          GLQ          Unf       Gd   
3     None     1Fam       Gd           No          ALQ          Unf       TA   
4     None     1Fam       TA           Av          GLQ          Unf       Gd   
...    ...      ...      ...          ...          ...          ...      ...   
1454  None    Twnhs       TA           No          Unf          Unf       TA   
1455  None   TwnhsE       TA           No          Rec          Unf       TA   
1456  None     1Fam       TA           No          ALQ          Unf       TA   
1457  None     1Fam       TA           Av          GLQ          Unf       Gd   
1458  None     1Fam       TA           Av          LwQ          Unf       Gd   

     CentralAir Condition1 Condition2  ... MiscFeature Neighborhood  \
0             Y       Norm       Norm  ...        None      CollgCr   
1             Y      Feedr       Norm  ...        None      Veenker   
2             Y       Norm       Norm  ...        None      CollgCr   
3             Y       Norm       Norm  ...        None      Crawfor   
4             Y       Norm       Norm  ...        None      NoRidge   
...         ...        ...        ...  ...         ...          ...   
1454          Y       Norm       Norm  ...        None      MeadowV   
1455          Y       Norm       Norm  ...        None      MeadowV   
1456          Y       Norm       Norm  ...        None      Mitchel   
1457          Y       Norm       Norm  ...        Shed      Mitchel   
1458          Y       Norm       Norm  ...        None      Mitchel   

     PavedDrive PoolQC RoofMatl RoofStyle SaleCondition SaleType Street  \
0             Y   None  CompShg     Gable        Normal       WD   Pave   
1             Y   None  CompShg     Gable        Normal       WD   Pave   
2             Y   None  CompShg     Gable        Normal       WD   Pave   
3             Y   None  CompShg     Gable       Abnorml       WD   Pave   
4             Y   None  CompShg     Gable        Normal       WD   Pave   
...         ...    ...      ...       ...           ...      ...    ...   
1454          Y   None  CompShg     Gable        Normal       WD   Pave   
1455          Y   None  CompShg     Gable       Abnorml       WD   Pave   
1456          Y   None  CompShg     Gable       Abnorml       WD   Pave   
1457          Y   None  CompShg     Gable        Normal       WD   Pave   
1458          Y   None  CompShg     Gable        Normal       WD   Pave   

     Utilities  
0       AllPub  
1       AllPub  
2       AllPub  
3       AllPub  
4       AllPub  
...        ...  
1454    AllPub  
1455    AllPub  
1456    AllPub  
1457    AllPub  
1458    AllPub  

[2919 rows x 43 columns]

In [25]:
#Data_train=AllData[:1460]

#Data_test=AllData[1460:]

#Data_test.drop('SalePrice',inplace=True,axis=1)

# Linear Regression Model

In [26]:
Data_train

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0        1          60       RL         65.0     8450   Pave   NaN      Reg   
1        2          20       RL         80.0     9600   Pave   NaN      Reg   
2        3          60       RL         68.0    11250   Pave   NaN      IR1   
3        4          70       RL         60.0     9550   Pave   NaN      IR1   
4        5          60       RL         84.0    14260   Pave   NaN      IR1   
...    ...         ...      ...          ...      ...    ...   ...      ...   
1455  1456          60       RL         62.0     7917   Pave   NaN      Reg   
1456  1457          20       RL         85.0    13175   Pave   NaN      Reg   
1457  1458          70       RL         66.0     9042   Pave   NaN      Reg   
1458  1459          20       RL         68.0     9717   Pave   NaN      Reg   
1459  1460          20       RL         75.0     9937   Pave   NaN      Reg   

     LandContour Utilities  ... PoolArea PoolQC  Fence MiscFeature MiscVal  \
0            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
2            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
3            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
4            Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
...          ...       ...  ...      ...    ...    ...         ...     ...   
1455         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1456         Lvl    AllPub  ...        0    NaN  MnPrv         NaN       0   
1457         Lvl    AllPub  ...        0    NaN  GdPrv        Shed    2500   
1458         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   
1459         Lvl    AllPub  ...        0    NaN    NaN         NaN       0   

     MoSold YrSold  SaleType  SaleCondition  SalePrice  
0         2   2008        WD         Normal     208500  
1         5   2007        WD         Normal     181500  
2         9   2008        WD         Normal     223500  
3         2   2006        WD        Abnorml     140000  
4        12   2008        WD         Normal     250000  
...     ...    ...       ...            ...        ...  
1455      8   2007        WD         Normal     175000  
1456      2   2010        WD         Normal     210000  
1457      5   2010        WD         Normal     266500  
1458      4   2010        WD         Normal     142125  
1459      6   2008        WD         Normal     147500  

[1460 rows x 81 columns]

In [28]:
X=AllData[:1460]
X=X.drop('SalePrice',axis=1)
y=AllData[:1460]['SalePrice']

In [32]:
len(X)

1460

In [33]:
len(y)

1460

In [31]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(X, y)
reg.score(X, y)

ValueError: could not convert string to float: 'RL'

In [ ]:
Data_test=AllData[1460:]
Data_test=Data_test.drop('SalePrice',axis=1)

In [ ]:
price=reg.predict(data_test)
Data_res=Data_test[['Id','MSSubClass']]
Data_res['SalePrice']=price
Data_res.drop('MSSubClass',axis=1,inplace=True)
Data_res.to_csv('LinearReg2.csv',index=False)